services:
  mc:
    image: itzg/minecraft-server:java21-alpine
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: SPIGOT
      VERSION: 1.21
      MEMORY: 2G
      MOTD: Dev server
      ENABLE_COMMAND_BLOCK: true

    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./minecraft-data:/data